### ISSUE TITLE
01 Create simple markup

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#1]
## Create the first page with simple html markup in my App.js

The start page should inform the user about the app and its content: it's all about great coffee! 

<img width="258" alt="Screenshot 2022-04-27 at 15 44 41" src="https://user-images.githubusercontent.com/100590328/165532880-bbb0aee9-f212-4067-adb1-d32be39cd5f6.png">

## Acceptance criteria

- [ ] The page should have an header displaying the app name, 
- [ ] The page should have a main part with a coffee picture and some information about the app
- [ ] The page should have a navbar but the links right now are just placeholders!

## Tasks

- [ ] create header html markup
- [ ] create main with coffee image and information about coffee and the app (what can user expect?)
- [ ] create navbar html: the links right now are just placeholders

## Size

small

**Comment by Sanae-G** [comment]
Hi Daniele, very nice layout! Regarding the navbar you should only display the home icon because the other nav icons/button do not work in this state (this is not recommended as i know from my experience). You should only show the user what's really working on your app. The other buttons will appear step by step in your future user stories! :D

**Comment by PReichetanz** [comment]
> Hi Daniele, very nice layout! Regarding the navbar you should only display the home icon because the other nav icons/button do not work in this state (this is not recommended as i know from my experience). You should only show the user what's really working on your app. The other buttons will appear step by step in your future user stories! :D

True, but remove the navbar here completely because it serves no purpose then ;)
