### ISSUE TITLE
05 Create Shopping Basket Page

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#11]
## Value proposition

As a **User**
I want to **select a product and move it to my shopping basket**
in order to **be able to order it if I want to**.

## Description
Create a Shopping Basket Page with a counter:

<img width="905" alt="Screenshot 2022-05-12 at 09 28 59" src="https://user-images.githubusercontent.com/100590328/168016020-14bba66a-600f-4638-9937-896394d2780b.png">

## Acceptance criteria

- [x] "Add to basket" button on Product Page should add the selected coffee to the shopping basket
- [x] Shopping basket should show the products added to it and have a counter functionality
- [x] It should also be possible to delete products from the basket
- [x] The header should have a new link leading to the shopping basket
- [x] The products added to the basket should remain in the basket using Local Storage

## Tasks

- [x] create Shopping Basket Page
- [x] create "add to basket" button on Product Page 
- [x] create new link for the header section leading to Shopping basket
- [x] add local storage functionality to shopping basket
- [x] add counter functionality to Shopping basket
- [x] add delete button for the products

## Size

large

**Comment by PReichetanz** [comment]
Hi Daniele,
looks really good!
Just one thing: I cannot see the delete button, where do you want to display it?

**Comment by DanCesca** [comment]
Hi Paul! Thank you very much for your feedback. I forgot indeed to add the delete button to the design. :) you can see it now in the description pic.

**Comment by PReichetanz** [comment]
Hi Daniele, very nice, I think you are ready to go now ;)
