### ISSUE TITLE
06 Create Favourite Page

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#14]
## Value proposition

As a **User**
I want to **save products as favourites**
in order to **be able to order them later on**.

## Description
Create a Favourite Page:

<img width="1164" alt="Screenshot 2022-05-16 at 15 58 33" src="https://user-images.githubusercontent.com/100590328/168609789-27a17181-d0a6-4ad1-8a5e-2daecab7e55a.png">

## Acceptance criteria

- [x] It should be possible to add an item to the favourite list
- [x] The navbar should have a new link leading to the Favourite Page
- [x] The favourite page should show all items selected as favourites
- [x] It should be possible to toggle the status of an item between favourite/not favourite
- [x] It should be possible to move an item from favourite page to the shopping cart
- [x] The favourite state of an item should persist using Local Storage

## Tasks

- [x] Create Favourite Page component rendering a list of items
- [x] Add "add to favourites" button to products with toggle function
- [x] Create new link for the Navbar leading to Favourite Page
- [x] Add delete button for favourite items
- [x] Add "add to cart" button to favourite items
- [x] add local storage functionality to favourites

## Size

large

**Comment by mbosselmann** [comment]
Hi Daniele,
I like your user story! 👍 
Happy hacking!

**Comment by DanCesca** [comment]
Hi Mareike, 
Thank you very much! 😄
