### ISSUE TITLE
01 Create Taste Page 

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#2]
## Value proposition

As a **User**
I want to **learn more about the different roast levels and tastes of coffee**
in order to **be able to select the coffee that matches my taste**.

## Description
Install styled components and create first card component. Use card component to create three cards with different roast levels (light, medium and dark) with a picture and some information about the respective roast  level. At this point there will be still no header nor navbar and also no buttons:

<img width="593" alt="Screenshot 2022-04-28 at 12 14 06" src="https://user-images.githubusercontent.com/100590328/165730960-1448629b-b961-4e5e-95ef-5bf72594fbd7.png">

## Acceptance criteria

- [x] Page should show three cards with same layout: picture, title and description

## Tasks

- [x] install styled-components
- [x] create card component
- [x] create three cards for the different roast levels with pic, title and description. Data is hard coded at this stage.

## Size

small

**Comment by PReichetanz** [comment]
## Value proposition
- Please the scheme as mentioned in my comment of #1 
- Where is this "Explore by taste" button? It is not part of your design description as far as I can see.
- How am I as a user supposed to "read about the different roast levels and tastes of coffee" if there are big pictures with only a headline and a one-liner below it? Do you have a special design in mind but did not show it?

## General
- It seems to me that this is more like your core function than #1; you could render information of roast levels etc. as first story.
- Please remove the unused parts of your navbar.
- Why didn't you make styled-components part of your first story and create components from the very beginning instead of "converting into component"?
