### ISSUE TITLE
02 Create Detail Page

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#3]
## Value proposition

As a **User**
I want to **learn more about a particular roast level**
in order to **understand if it's the right choice.**.

## Description
Create button to read more about a specific roast level. Then modify the existing card component to show more details "Onclick" (picture and some more information about the roast level and a coffee example).  Also add a toggle function to the Button so that user can close the card:

<img width="1001" alt="Screenshot 2022-05-03 at 10 14 08" src="https://user-images.githubusercontent.com/100590328/166422594-6c4f0bca-95ea-4b10-8fd2-27d03c40b584.png">

## Acceptance criteria

- [x] Select button on Taste page should expand the card and show more details
- [x] Detail card should show more info about the selected roast level and a coffee example with picture
- [x] Button should toggle between Select/Close

## Tasks

- [x] create button component 
- [x] add data for example coffees to the database.js
- [x] modify card component to show more details Onclick
- [x] add toggle function to the button

## Size

large

**Comment by PReichetanz** [comment]
Almost there! 🚀

- "...in order to understand if it's the right choice." (You don't need the second sentence here)
- You have already installed styled-components in #2 ;) 
- Task 4 (create three detail cards...): Is already done with #2 .
