### ISSUE TITLE
03 Create Header and Navigation

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#4]
## Value proposition

As a **User**
I want to **have a header section and a navigation**
in order to **understand where I am and be able to navigate through the app**.

## Description
Create a header component and a navigation with a Home Button. At this stage there are no other pages than the home page = Taste page. 

<img width="566" alt="Screenshot 2022-05-05 at 14 53 38" src="https://user-images.githubusercontent.com/100590328/166927930-126f26d4-81b0-457c-b387-3a8b0ba8f19d.png">

## Acceptance criteria

- [x] Header should display name of the App (World of Coffee) on the left 
- [x] Navigation should show a Home Button linking to localhost:3000, which is the home page and the Taste Page at the same time

## Tasks

- [x] install react-router
- [x] create Header component 
- [x] create NavBar component
- [x] add routing to index.js and app.js
- [x] add NavLink to NavBar
- [x] Check functionality

## Size

medium

**Comment by PReichetanz** [comment]
Remark on UX:
- If you make the "world of coffee" headline in screen 2 smaller and adjacent to the left, how does the user know that it is clickable? And why do you still need the back button at the bottom then?

- You don't need a second header component here, you can simply render your header differently dependent on a prop you hand down (e.g. `isHomeHeader={true}`).

**Comment by DanCesca** [comment]
That's a good point! 

- What about having the back button in the header for all other pages instead of a downsized version of "world of coffee"? i changed the story accordingly.

**Comment by CJAkkuec** [comment]
Good idea, although I'd suggest that you might want to include what the button does and/or where it routes to. Such as: < Back, < Home, etc.
Depending on your App structure, your App might benefit from having the title inside the header display what page you're on. Otherwise navigation might get a little confusing. Either that, or handle navigation with a navbar at the bottom that highlights the icon of the page you're on, etc. It's just a matter of what you want to do. : )

**Comment by DanCesca** [comment]
Thank you very much for your feedback! Indeed, I'm planning a navbar later on so this is probably perfect as a < Back button. ;)
