### ISSUE TITLE
04 Create Product Page

### ISSUE THREAD

**Issue by DanCesca** [DanCesca/capstone-worldofcoffee#6]
## Value proposition

As a **User**
I want to **learn more about the selected product**
in order to **decide if I want to order it or not**.

## Description
Create a Product Page with detailed information about the product and other picks:
- At this stage the user will learn more about the selected product, but still won't be able to add it to its basket (no button for this functionality yet)
- However, The user can select another coffee from the picks and is redirected to the corresponding product page:

<img width="1201" alt="Screenshot 2022-05-05 at 16 06 25" src="https://user-images.githubusercontent.com/100590328/166941134-86720a6f-6f4b-4db0-8967-c5f7089e5f35.png">

## Acceptance criteria

- [x] "Select" button on Detail Card should lead to coffee product page
- [x] Product page should show detailed information about the corresponding coffee
- [x] At the bottom of the page, a new component "Other picks" should display other similar coffees and the user should be able to click on "Select" button and move to the corresponding coffee page

## Tasks

- [x] create Product Page 
- [x] create other Header version with a back button using a prop {isHomeHeader = (true or false)} and add it to Product Page
- [x] add Select button to Detail Card with link to coffee product page
- [x] create OtherPicks component with Select buttons and add it to coffee product page
- [x] add filter functionality to OtherPicks component to be able to display similar coffees
- [x] add testing

## Size

large

**Comment by mbosselmann** [comment]
Hi Daniele,

I like your user story and only have two suggestions for the tasks section:

- You could add storybook and testing as tasks
- If I did understand it correctly you want to display similar coffees with `OtherPicks`. Therefore, I think that you need a filter functionality that selects the right coffees for this component. Maybe this is worth to mention as extra task, but that is up to you to decide. :)

**Comment by DanCesca** [comment]
Hi Mareike,

Thank you very much for your feedback! 

- I decided to go without storybook, but I'm happy to add another test for sure! ;)
- Very good point, I will add it as a task.
